// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package protomodel is a generated protocol buffer package.

It is generated from these files:
	api.proto
	machinery.proto
	wiphone.proto

It has these top-level messages:
	Error
	TaskError
	TaskStateResponse
	Credentials
	ConsumptionResponse
	AnonymousConsumptionRequest
*/
package protomodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Code        int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "protomodel.Error")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0xb9, 0xf9, 0x29, 0xa9, 0x39, 0x4a, 0xb6,
	0x5c, 0xac, 0xae, 0x45, 0x45, 0xf9, 0x45, 0x42, 0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0xb6, 0x90, 0x02, 0x17, 0xb7, 0x4b, 0x6a, 0x71, 0x72,
	0x51, 0x66, 0x41, 0x49, 0x66, 0x7e, 0x9e, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0xb2, 0x50,
	0x12, 0x1b, 0xd8, 0x28, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0xd3, 0x93, 0xe1, 0x5e,
	0x00, 0x00, 0x00,
}
